domain: warpgate.com
url: https://warpgate.com
#baseurl: "/wuyuling"

title: Home
email: wuyuling@warpgate.cn
author: Wu Yu Ling

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "wuyuling@warpgate.cn"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
